#!/usr/bin/env bash

# A resource type's check script is invoked to detect new versions
# of the resource. It is given the configured source and current
# version on stdin, and must print the array of new versions, in
# chronological order, to stdout, including the requested version
# if it's still valid.

set -euo pipefail
"$(dirname "$0")"/lib/commands/check.py
